### ISSUE TITLE
Request for Missing Stats Files for AFHQ-CAT

### ISSUE THREAD

**Issue by aiihn** [nguyenngocbaocmt02/BOSS#1]
Thank you very much for your great work!

It appears that the stats files for AFHQ-CAT are missing in the [Google Drive link](https://drive.google.com/drive/folders/1rNF6jJ5T1UNpLTkuEqwIrFdq9vyw5Cbj) you provided. Could you please provide them?

> For CelebA HQ (256) and LSUN, please check out [here](https://github.com/NVlabs/NVAE#set-up-file-paths-and-data) for dataset preparation.
> 
> For AFHQ-CAT, please check out [here](https://github.com/clovaai/stargan-v2-tensorflow/tree/master).
> 
> We also provide stats files for these datasets at [here](https://drive.google.com/drive/folders/1rNF6jJ5T1UNpLTkuEqwIrFdq9vyw5Cbj). Store these stats files in the folder stats which is in the cleanfid installed folder (`~/anaconda3/envs/boss/lib/python3.9/site-packages/cleanfid/stats`).

Thank you for your kindness!

**Comment by nguyenngocbaocmt02** [comment]
Hello aiihn, It seems there was an error in our previous upload of the AFHQ-CAT stats file. It is now available in the Google Drive link. We appreciate your kind reminder. Thank you, and have a good day!

**Comment by aiihn** [comment]
Thank you very much! I have successfully downloaded the updated file from the Google Drive link. Your quick response are greatly appreciated!

Best regards,
aiihn
